### ISSUE TITLE
Country picker is blank

### ISSUE THREAD

**Issue by mikemandolin** [kadegray/statamic-country-and-region-fieldtypes#7]
The country picker dropdown appears blank when editing an entry:

<img width="873" alt="Screenshot 2024-03-06 at 18 38 16" src="https://github.com/kadegray/statamic-country-and-region-fieldtypes/assets/77166869/f2a11c83-fe4f-4d47-9dbd-cb73910d4e1b">

**Comment by mikemandolin** [comment]
<img width="934" alt="Screenshot 2024-03-07 at 09 51 23" src="https://github.com/kadegray/statamic-country-and-region-fieldtypes/assets/77166869/2a1cad17-d5eb-452d-a03c-1d419422ff24">

`Error: Call to undefined function bindtextdomain() in file /Users/mts/Herd/mcx-innovation/vendor/sokil/php-isocodes/src/TranslationDriver/GettextExtensionDriver.php on line 12`

**Comment by kadegray** [comment]
@mikemandolin Thanks for reporting this and providing the php error. I'll have to investigate this further.

Is this error occurring consistently for you?

If it is consistent I just want to confirm something, could you please provide the data submitted in the XHR requests to !/statamic-country-and-region-fieldtypes/countries.

**Comment by mikemandolin** [comment]
hi @kadegray - thanks for investigating! here is the request:

**Request**
```
:method: POST
:scheme: https
:authority: mcx-innovation.test
:path: /!/statamic-country-and-region-fieldtypes/countries
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Content-Length: 0
Cookie: XSRF-TOKEN=<my token>
Host: mcx-innovation.test
Origin: https://mcx-innovation.test
Referer: https://mcx-innovation.test/cp/collections/pages/entries/210346d1-d722-476d-9eab-0746c0dcd7ef
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3.1 Safari/605.1.15
X-CSRF-Token: <token>
```
**Response**
```
:status: 500
Cache-Control: no-cache, private
Content-Type: text/html; charset=UTF-8
Date: Wed, 13 Mar 2024 14:21:25 GMT
permissions-policy: interest-cohort=()
Server: nginx/1.25.4
Set-Cookie: XSRF-TOKEN=<my token>  expires=Wed, 13 Mar 2024 16:21:25 GMT; Max-Age=7200; path=/; secure; samesite=lax
Set-Cookie: statamic_session=<my session> expires=Wed, 13 Mar 2024 16:21:25 GMT; Max-Age=7200; path=/; httponly; samesite=lax
x-powered-by: PHP/8.3.3, Statamic
```

**and the stack trace**
```
Error: Call to undefined function bindtextdomain() in file /Users/mts/Herd/mcx-innovation/vendor/sokil/php-isocodes/src/TranslationDriver/GettextExtensionDriver.php on line 12

#0 /Users/mts/Herd/mcx-innovation/vendor/sokil/php-isocodes/src/AbstractDatabase.php(88): Sokil\IsoCodes\TranslationDriver\GettextExtensionDriver-&gt;configureDirectory(&#039;3166-1&#039;, &#039;/Users/mts/Herd...&#039;)
#1 /Users/mts/Herd/mcx-innovation/vendor/sokil/php-isocodes/src/IsoCodesFactory.php(76): Sokil\IsoCodes\AbstractDatabase-&gt;__construct(NULL, Object(Sokil\IsoCodes\TranslationDriver\GettextExtensionDriver))
#2 /Users/mts/Herd/mcx-innovation/vendor/kadegray/statamic-country-and-region-fieldtypes/src/Controllers/CountryFieldtypeController.php(20): Sokil\IsoCodes\IsoCodesFactory-&gt;getCountries()
#3 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Kadegray\StatamicCountryAndRegionFieldtypes\Controllers\CountryFieldtypeController-&gt;getOptions()
#4 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\Routing\Controller-&gt;callAction(&#039;getOptions&#039;, Array)
#5 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\Routing\ControllerDispatcher-&gt;dispatch(Object(Illuminate\Routing\Route), Object(Kadegray\StatamicCountryAndRegionFieldtypes\Controllers\CountryFieldtypeController), &#039;getOptions&#039;)
#6 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route-&gt;runController()
#7 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Routing/Router.php(806): Illuminate\Routing\Route-&gt;run()
#8 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Routing\Router-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Routing\Middleware\SubstituteBindings-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#13 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\View\Middleware\ShareErrorsFromSession-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#15 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession-&gt;handleStatefulRequest(Object(Illuminate\Http\Request), Object(Illuminate\Session\Store), Object(Closure))
#17 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Session\Middleware\StartSession-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#18 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Cookie\Middleware\EncryptCookies-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\Pipeline\Pipeline-&gt;then(Object(Closure))
#24 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\Routing\Router-&gt;runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#25 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\Routing\Router-&gt;runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#26 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\Routing\Router-&gt;dispatchToRoute(Object(Illuminate\Http\Request))
#27 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\Routing\Router-&gt;dispatch(Object(Illuminate\Http\Request))
#28 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Foundation\Http\Kernel-&gt;Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#29 /Users/mts/Herd/mcx-innovation/vendor/statamic/cms/src/Http/Middleware/StopImpersonating.php(12): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\Http\Middleware\StopImpersonating-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /Users/mts/Herd/mcx-innovation/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(17): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\Http\Middleware\DisableFloc-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /Users/mts/Herd/mcx-innovation/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\Http\Middleware\CheckMultisite-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /Users/mts/Herd/mcx-innovation/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\Http\Middleware\CheckComposerJsonScripts-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /Users/mts/Herd/mcx-innovation/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(18): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\Http\Middleware\PoweredByHeader-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /Users/mts/Herd/mcx-innovation/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(59): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Barryvdh\Debugbar\Middleware\InjectDebugbar-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\TrimStrings-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\ValidatePostSize-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Http\Middleware\HandleCors-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Http\Middleware\TrustProxies-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#55 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\Pipeline\Pipeline-&gt;then(Object(Closure))
#57 /Users/mts/Herd/mcx-innovation/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\Foundation\Http\Kernel-&gt;sendRequestThroughRouter(Object(Illuminate\Http\Request))
#58 /Users/mts/Herd/mcx-innovation/public/index.php(51): Illuminate\Foundation\Http\Kernel-&gt;handle(Object(Illuminate\Http\Request))
#59 /Applications/Herd.app/Contents/Resources/valet/server.php(151): require(&#039;/Users/mts/Herd...&#039;)
#60 {main}
```

**Comment by mikemandolin** [comment]
one note to add: this problem appears in the control panel only. 

if I use the `countries_and_regions` tag on the front end, it displays a list of all countries as expected with your example:

```
<ul>
{{ countries_and_regions:countries default="AU" }}
    <li>{{ isoCode }} - {{ countryName }}</li>
{{ /countries_and_regions:countries }}
</ul>
```

**Comment by kadegray** [comment]
@mikemandolin I think that if you look at your phpinfo your GetText Support might be false. Which means the getext php extension is not installed which is the issue. But i'm not sure how this can happen by default.

**Comment by mikemandolin** [comment]
thank you @kadegray - it appears that GetText is not included in Herd for local dev. The add-on works as expected on our live environments however! 

I've been unsuccessful with including a GetText php module locally however.

**Comment by kadegray** [comment]
@mikemandolin If you find a solution to GetText being missing from Herd, do you mind writing a comment about it on this issue?

**Comment by kadegray** [comment]
This is a known issue with Herd, there are a number of php extensions missing from Herd. Please see this issue for more information and hopefully a solution before to long: https://github.com/beyondcode/herd-community/issues/16
